name: Build Debian Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Build Debian Package
        run: |
          COMMIT=$(git rev-parse HEAD | head -c 7)
          cd /tmp; git clone -b develop https://github.com/fade-project/fade
          cd fade; npm install 
          ./main.js --init --name xenxenxense --path $GITHUB_WORKSPACE --version 0.0.0-$COMMIT-$PYTHON_VERSION \
          --description "A Modern RESTful API implemenation of XenAPI for Citrix Hypervisor(R) and XCP-ng." \
          --url "https://github.com/Stella-IT/XenXenXenSe" --priority optional --architecture all \
          --cmdline "python3 -m pipenv run start" --dependancy python$PYTHON_VERSION \
          --maintainer-name "Stella IT" --maintainer-email "admin@stella-it.com" --type systemd
          ./main.js --edit --path $GITHUB_WORKSPACE --postinst-payload -i /dev/stdin << EOF
          sudo -H -u xenxenxense python3 -m pip install pipenv
          sudo -H -u xenxenxense bash -c "cd /usr/lib/xenxenxense/;python3 -m pipenv install"
          echo "WARNING: config.py is currently default; please edit before use."
          EOF
          ./main.js --create-deb --path $GITHUB_WORKSPACE
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: Upload Debian Package
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Debian Package - ${{ matrix.python-version }}
          # A file, directory or wildcard pattern that describes what to upload
          path: xenxenxense_0.0.0-*_all.deb
      - name: Test Debian Package
        run: |
          COMMIT=$(git rev-parse HEAD | head -c 7)
          sudo dpkg --ignore-depends=python$PYTHON_VERSION -i $GITHUB_WORKSPACE/xenxenxense_0.0.0-$COMMIT-$PYTHON_VERSION\_all.deb